AWSTemplateFormatVersion: '2010-09-09'
Description: 'ISB Deployer - Cross-Account Role for Sandbox Sub-Accounts (deployed via StackSet)'

# This template creates an IAM role in each sandbox sub-account that:
# 1. Trusts the ISB Deployer Lambda role from the hub account
# 2. Has permissions to deploy CloudFormation stacks
# 3. Is completely independent of the main ISB solution
#
# Deploy this template to sandbox accounts using CloudFormation StackSets
# from the hub account or AWS Organizations management account.

Parameters:
  DeployerRoleArn:
    Type: String
    Description: 'ARN of the ISB Deployer Lambda role in the hub account that will assume this role'
    AllowedPattern: 'arn:aws:iam::\d{12}:role/.+'
    ConstraintDescription: 'Must be a valid IAM role ARN'

  RoleName:
    Type: String
    Default: 'InnovationSandbox-ndx-DeployerRole'
    Description: 'Name of the IAM role to create in sandbox accounts. Must match InnovationSandbox-{namespace}* to be exempt from SCPs.'
    MinLength: 1
    MaxLength: 64
    AllowedPattern: 'InnovationSandbox-[a-zA-Z0-9]+-[a-zA-Z0-9_-]+'
    ConstraintDescription: 'Must match InnovationSandbox-{namespace}-* pattern to be exempt from SCPs'

Resources:
  # IAM Role that the deployer Lambda will assume in sandbox accounts
  SandboxDeployerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      Description: 'Role for ISB Deployer to deploy CloudFormation stacks in this sandbox account'
      MaxSessionDuration: 3600  # 1 hour
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref DeployerRoleArn
            Action: 'sts:AssumeRole'
            # Optional: Add conditions for extra security
            # Condition:
            #   StringEquals:
            #     'sts:ExternalId': 'isb-deployer'
      Policies:
        # CloudFormation permissions for deploying stacks
        - PolicyName: CloudFormationDeployment
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Full CloudFormation access for the deployer
              - Effect: Allow
                Action:
                  - 'cloudformation:CreateStack'
                  - 'cloudformation:UpdateStack'
                  - 'cloudformation:DeleteStack'
                  - 'cloudformation:DescribeStacks'
                  - 'cloudformation:DescribeStackEvents'
                  - 'cloudformation:DescribeStackResources'
                  - 'cloudformation:GetTemplate'
                  - 'cloudformation:GetTemplateSummary'
                  - 'cloudformation:ValidateTemplate'
                  - 'cloudformation:ListStacks'
                  - 'cloudformation:ListStackResources'
                  - 'cloudformation:CreateChangeSet'
                  - 'cloudformation:DescribeChangeSet'
                  - 'cloudformation:ExecuteChangeSet'
                  - 'cloudformation:DeleteChangeSet'
                  - 'cloudformation:SetStackPolicy'
                Resource: '*'

              # Pass role for CloudFormation service role (if stacks use one)
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource: '*'
                Condition:
                  StringEquals:
                    'iam:PassedToService': 'cloudformation.amazonaws.com'

        # Resource creation permissions for common scenario resources
        # This is a broad permission set to allow scenario templates flexibility
        # In production, consider restricting based on actual scenario requirements
        - PolicyName: ScenarioResourceCreation
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # Common services used in sandbox scenarios
              - Effect: Allow
                Action:
                  # S3
                  - 's3:*'
                  # Lambda
                  - 'lambda:*'
                  # API Gateway
                  - 'apigateway:*'
                  # DynamoDB
                  - 'dynamodb:*'
                  # SNS
                  - 'sns:*'
                  # SQS
                  - 'sqs:*'
                  # CloudWatch
                  - 'logs:*'
                  - 'cloudwatch:*'
                  # EC2 (for VPC resources)
                  - 'ec2:*'
                  # IAM for creating roles within the sandbox
                  - 'iam:*'
                  # Secrets Manager
                  - 'secretsmanager:*'
                  # SSM Parameter Store
                  - 'ssm:*'
                  # Step Functions
                  - 'states:*'
                  # EventBridge
                  - 'events:*'
                  # Bedrock (for AI scenarios)
                  - 'bedrock:*'
                  # SageMaker
                  - 'sagemaker:*'
                Resource: '*'
      Tags:
        - Key: Application
          Value: 'isb-deployer'
        - Key: ManagedBy
          Value: 'CloudFormation-StackSet'
        - Key: Purpose
          Value: 'Cross-account CloudFormation deployment'

Outputs:
  RoleArn:
    Description: 'ARN of the sandbox deployer role'
    Value: !GetAtt SandboxDeployerRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'

  RoleName:
    Description: 'Name of the sandbox deployer role'
    Value: !Ref SandboxDeployerRole
    Export:
      Name: !Sub '${AWS::StackName}-RoleName'
