AWSTemplateFormatVersion: '2010-09-09'
Description: 'Innovation Sandbox on AWS Deployer - Lambda Function and Infrastructure'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Environment Configuration'
        Parameters:
          - Environment
      - Label:
          default: 'Data Storage'
        Parameters:
          - LeaseTableName
      - Label:
          default: 'GitHub Repository Configuration'
        Parameters:
          - GithubRepo
          - GithubBranch
          - GithubPath
      - Label:
          default: 'Cross-Account Access'
        Parameters:
          - TargetRoleName
      - Label:
          default: 'Event Configuration'
        Parameters:
          - EventSource
      - Label:
          default: 'Deployment Artifacts'
        Parameters:
          - ArtifactBucket
          - ArtifactKey
    ParameterLabels:
      Environment:
        default: 'Deployment Environment'
      LeaseTableName:
        default: 'Lease DynamoDB Table Name'
      GithubRepo:
        default: 'GitHub Repository (owner/name)'
      GithubBranch:
        default: 'GitHub Branch'
      GithubPath:
        default: 'GitHub Path to Templates'
      TargetRoleName:
        default: 'Target IAM Role Name'
      EventSource:
        default: 'EventBridge Source Filter'
      ArtifactBucket:
        default: 'S3 Artifact Bucket'
      ArtifactKey:
        default: 'S3 Artifact Key'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues:
      - dev
      - staging
      - prod
    Description: 'Deployment environment (dev/staging/prod). Controls log level and resource naming.'
    ConstraintDescription: 'Must be one of: dev, staging, prod'

  LeaseTableName:
    Type: String
    Description: 'DynamoDB table name for lease data lookups. Must be an existing table accessible by the Lambda function.'
    Default: 'isb-leases'
    MinLength: 3
    MaxLength: 255
    AllowedPattern: '[a-zA-Z0-9_.-]+'
    ConstraintDescription: 'Must be a valid DynamoDB table name (3-255 chars, alphanumeric, dots, dashes, underscores)'

  GithubRepo:
    Type: String
    Description: 'GitHub repository in owner/name format where CloudFormation scenario templates are stored'
    Default: 'co-cddo/ndx_try_aws_scenarios'
    MinLength: 3
    MaxLength: 255
    AllowedPattern: '[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+'
    ConstraintDescription: 'Must be in format owner/repository (e.g., co-cddo/ndx_try_aws_scenarios)'

  GithubBranch:
    Type: String
    Description: 'GitHub branch to fetch templates from. Defaults to main branch.'
    Default: 'main'
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '[a-zA-Z0-9_./+-]+'
    ConstraintDescription: 'Must be a valid Git branch name (alphanumeric, dots, slashes, dashes, underscores, plus signs)'

  GithubPath:
    Type: String
    Description: 'Path within the repository to scenario templates directory (without leading/trailing slashes)'
    Default: 'cloudformation/scenarios'
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '[a-zA-Z0-9_./+-]+'
    ConstraintDescription: 'Must be a valid path (alphanumeric, dots, slashes, dashes, underscores, plus signs)'

  TargetRoleName:
    Type: String
    Description: 'IAM role name to assume in target sub-accounts for CloudFormation deployment operations'
    Default: 'ndx_IsbUsersPS'
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '[a-zA-Z0-9+=,.@_-]+'
    ConstraintDescription: 'Must be a valid IAM role name (1-64 chars, alphanumeric and +=,.@_-)'

  EventSource:
    Type: String
    Default: 'innovation-sandbox'
    Description: 'EventBridge event source to filter for lease approved events. Must match the source field in incoming events.'
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '[a-zA-Z0-9_.-]+'
    ConstraintDescription: 'Must be a valid EventBridge source name (alphanumeric, dots, dashes, underscores)'

  ArtifactBucket:
    Type: String
    Description: 'S3 bucket name containing the Lambda deployment package (.zip file). Must be in the same region as the stack.'
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '[a-z0-9][a-z0-9.-]*[a-z0-9]'
    ConstraintDescription: 'Must be a valid S3 bucket name (3-63 chars, lowercase alphanumeric, dots, dashes, start/end with alphanumeric)'

  ArtifactKey:
    Type: String
    Description: 'S3 object key for the Lambda deployment package (.zip file)'
    Default: 'lambda/handler.zip'
    MinLength: 1
    MaxLength: 1024
    AllowedPattern: '[a-zA-Z0-9_./+-]+'
    ConstraintDescription: 'Must be a valid S3 object key (alphanumeric, dots, slashes, dashes, underscores, plus signs)'

Conditions:
  IsProd: !Equals [!Ref Environment, 'prod']
  IsNotProd: !Not [!Condition IsProd]

Resources:
  # Lambda Function for deploying CloudFormation templates
  DeployerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'isb-deployer-${Environment}'
      Description: 'Deploys CloudFormation templates to Innovation Sandbox sub-accounts on lease approval'
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Handler: handler.handler
      MemorySize: 256
      Timeout: 60
      Role: !GetAtt DeployerRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Ref ArtifactKey
      Environment:
        Variables:
          LEASE_TABLE_NAME: !Ref LeaseTableName
          GITHUB_REPO: !Ref GithubRepo
          GITHUB_BRANCH: !Ref GithubBranch
          GITHUB_PATH: !Ref GithubPath
          TARGET_ROLE_NAME: !Ref TargetRoleName
          AWS_REGION: !Ref 'AWS::Region'
          EVENT_SOURCE: 'isb-deployer'
          LOG_LEVEL: !If [IsProd, 'INFO', 'DEBUG']
      Tags:
        - Key: Application
          Value: 'innovation-sandbox-deployer'
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: 'CloudFormation'

  # IAM Role for Lambda Execution
  # Follows least privilege principle with specific permissions for:
  # - DynamoDB read access for lease lookups
  # - STS AssumeRole for cross-account deployment
  # - EventBridge PutEvents for status notifications
  # - CloudWatch Logs via AWSLambdaBasicExecutionRole
  DeployerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'isb-deployer-role-${Environment}'
      Description: 'IAM role for Innovation Sandbox Deployer Lambda'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        # DynamoDB read-only access for lease table lookups
        - PolicyName: DynamoDBReadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:GetItem'
                  - 'dynamodb:Query'
                Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${LeaseTableName}'

        # STS permissions for cross-account role assumption
        # Allows assuming the target role in sub-accounts for CloudFormation deployment
        - PolicyName: STSAssumeRoleAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'sts:AssumeRole'
                Resource: !Sub 'arn:aws:iam::*:role/${TargetRoleName}'
                # Note: Wildcard (*) allows assuming role in any account
                # This is necessary for multi-account sandbox architecture
                # Consider adding aws:PrincipalOrgID condition for additional security

        # EventBridge permissions for deployment status events
        - PolicyName: EventBridgePutEvents
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'events:PutEvents'
                Resource: !Sub 'arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/default'

      Tags:
        - Key: Application
          Value: 'innovation-sandbox-deployer'
        - Key: Environment
          Value: !Ref Environment

  # EventBridge Rule for Lease Approved Events
  # Filters events from the innovation-sandbox source with detail-type 'Lease Approved'
  # and triggers the DeployerFunction Lambda
  LeaseApprovedRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'isb-deployer-lease-approved-${Environment}'
      Description: 'Triggers deployment when a lease is approved'
      EventBusName: default
      State: ENABLED
      EventPattern:
        source:
          - !Ref EventSource
        detail-type:
          - 'Lease Approved'
      Targets:
        - Id: DeployerLambdaTarget
          Arn: !GetAtt DeployerFunction.Arn
      Tags:
        - Key: Application
          Value: 'innovation-sandbox-deployer'
        - Key: Environment
          Value: !Ref Environment

  # Lambda Permission for EventBridge Invocation
  # Allows the EventBridge rule to invoke the Lambda function
  EventBridgeInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DeployerFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LeaseApprovedRule.Arn

Outputs:
  FunctionArn:
    Description: 'ARN of the deployer Lambda function'
    Value: !GetAtt DeployerFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionArn'

  FunctionName:
    Description: 'Name of the deployer Lambda function'
    Value: !Ref DeployerFunction
    Export:
      Name: !Sub '${AWS::StackName}-FunctionName'

  RoleArn:
    Description: 'ARN of the Lambda execution role'
    Value: !GetAtt DeployerRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'

  LeaseApprovedRuleArn:
    Description: 'ARN of the EventBridge rule for lease approved events'
    Value: !GetAtt LeaseApprovedRule.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LeaseApprovedRuleArn'

  LeaseApprovedRuleName:
    Description: 'Name of the EventBridge rule for lease approved events'
    Value: !Ref LeaseApprovedRule
    Export:
      Name: !Sub '${AWS::StackName}-LeaseApprovedRuleName'
